//
// Generated by dtk
// Translation Unit: d_a_obj_ospbox.cpp
//

#include "d/actor/d_a_obj_ospbox.h"
#include "d/d_com_inf_game.h"
#include "d/d_procname.h"
#include "d/d_priority.h"
#include "d/res/res_ospbox.h"
#include "m_Do/m_Do_mtx.h"

const char daObjOspbox::Act_c::M_arcname[] = "Ospbox";
const dCcD_SrcCyl daObjOspbox::Act_c::M_cyl_src = {
};

Mtx daObjOspbox::Act_c::M_tmp_mtx;

/* 000000EC-000001A0       .text CreateHeap__Q211daObjOspbox5Act_cFv */
BOOL daObjOspbox::Act_c::CreateHeap() {
    J3DModelData* model_data = (J3DModelData*)dComIfG_getObjectRes(M_arcname, OSPBOX_BDL_OSPBOX);
    JUT_ASSERT(0x186, model_data != NULL);
    mpModel = mDoExt_J3DModel__create(model_data,0x80000,0x11000022);
    return mpModel != NULL;
}

/* 000001A0-00000294       .text Create__Q211daObjOspbox5Act_cFv */
BOOL daObjOspbox::Act_c::Create() {
    //*(int *)(this + 0x22c) = *(int *)(this + 0x2d0) + 0x24;
    init_mtx();
    fopAcM_setCullSizeBox(this, -76.0f, -1.0f, -76.0f, 76.0f, 151.0f, 76.0f);
    mStts.Init(0xFF, 0xFF, this);
    mCyl.Set(M_cyl_src);

    //*(Act_c **)(this + 0x354) = this + 0x2d4;
    //*(float *)(this + 0x3c4) = ::cXyz::Zero.x;
    //*(float *)(this + 0x3c8) = ::cXyz::Zero.y;
    //*(float *)(this + 0x3cc) = ::cXyz::Zero.z;
    //*(uint *)(this + 0x3a4) = *(uint *)(this + 0x3a4) | 4;
    //*(float *)(this + 0x278) = *(float *)(this + 0x1fc) + 75.0;
    
    
    //*(undefined4 *)(this + 0x260) = *(undefined4 *)(this + 0x274);
    //*(undefined4 *)(this + 0x264) = *(undefined4 *)(this + 0x278);
    //*(undefined4 *)(this + 0x268) = *(undefined4 *)(this + 0x27c);
    // that means:
    // eyePos = attention_info.position;

    init_ground();

    //this[0x49a] = (Act_c)0x2;
    return TRUE;
}

/* 00000294-000004F8       .text Mthd_Create__Q211daObjOspbox5Act_cFv */
cPhs_State daObjOspbox::Act_c::Mthd_Create() {
    /* Nonmatching */
}

/* 00000BAC-00000BB4       .text Delete__Q211daObjOspbox5Act_cFv */
BOOL daObjOspbox::Act_c::Delete() {
    return TRUE;
}

/* 00000BB4-00000C04       .text Mthd_Delete__Q211daObjOspbox5Act_cFv */
BOOL daObjOspbox::Act_c::Mthd_Delete() {
    BOOL result = MoveBGDelete();
    dComIfG_deleteObjectRes(M_arcname);
    return result;
}

/* 00000C04-00000C84       .text set_mtx__Q211daObjOspbox5Act_cFv */
void daObjOspbox::Act_c::set_mtx() {
    MTXTrans(mDoMtx_stack_c::get(), current.pos.x, current.pos.y, current.pos.z);
    mDoMtx_ZXYrotM(mDoMtx_stack_c::get(), shape_angle.x, shape_angle.y, shape_angle.z);
    mpModel->setBaseTRMtx(mDoMtx_stack_c::get());
    PSMTXCopy(mDoMtx_stack_c::get(), M_tmp_mtx);
}

/* 00000C84-00000CC0       .text init_mtx__Q211daObjOspbox5Act_cFv */
void daObjOspbox::Act_c::init_mtx() {
    mpModel->setBaseScale(scale);
    set_mtx();
}

/* 00000CC0-00000D7C       .text make_item__Q211daObjOspbox5Act_cFv */
void daObjOspbox::Act_c::make_item() {
    /* Nonmatching */
}

/* 00000D7C-00000E78       .text eff_break__Q211daObjOspbox5Act_cFv */
void daObjOspbox::Act_c::eff_break() {
    /* Nonmatching */
}

/* 00000E78-00000F20       .text sound_break__Q211daObjOspbox5Act_cFv */
void daObjOspbox::Act_c::sound_break() {
    /* Nonmatching */
}

/* 00000F20-00000FE0       .text set_ground__Q211daObjOspbox5Act_cFv */
void daObjOspbox::Act_c::set_ground() {
    if (m498 <= 0) {
        return;
    }

    mGndChk.m_pos.set(current.pos.x, current.pos.y + 100.0f, current.pos.z);
    mGndChk.SetActorPid(this != NULL ? base.mBsPcId : 0xFFFFFFFF);
    
    m494 = dComIfG_Bgsp()->GroundCross(&mGndChk);
    if (m494 > -1e+09) {
        m498 = 0;
    } else {
        m498 = m498 - 1;
    }
}

/* 00000FE0-00001008       .text init_ground__Q211daObjOspbox5Act_cFv */
void daObjOspbox::Act_c::init_ground() {
    m498 = 5;
    set_ground();
}

/* 00001008-000010DC       .text Execute__Q211daObjOspbox5Act_cFPPA3_A4_f */
BOOL daObjOspbox::Act_c::Execute(Mtx**) {
    /* Nonmatching */
}

/* 000010DC-000011A4       .text Draw__Q211daObjOspbox5Act_cFv */
BOOL daObjOspbox::Act_c::Draw() {
    /* Nonmatching */
}

namespace daObjOspbox {
namespace {
/* 000011A4-000011C4       .text Mthd_Create__Q211daObjOspbox28@unnamed@d_a_obj_ospbox_cpp@FPv */
cPhs_State Mthd_Create(void* i_this) {
    return ((daObjOspbox::Act_c*)i_this)->Mthd_Create();
}

/* 000011C4-000011E4       .text Mthd_Delete__Q211daObjOspbox28@unnamed@d_a_obj_ospbox_cpp@FPv */
BOOL Mthd_Delete(void* i_this) {
    return ((daObjOspbox::Act_c*)i_this)->Mthd_Delete();
}

/* 000011E4-00001204       .text Mthd_Execute__Q211daObjOspbox28@unnamed@d_a_obj_ospbox_cpp@FPv */
BOOL Mthd_Execute(void* i_this) {
    return ((daObjOspbox::Act_c*)i_this)->MoveBGExecute();
}

/* 00001204-00001230       .text Mthd_Draw__Q211daObjOspbox28@unnamed@d_a_obj_ospbox_cpp@FPv */
BOOL Mthd_Draw(void* i_this) {
    return ((daObjOspbox::Act_c*)i_this)->Draw();
}

/* 00001230-0000125C       .text Mthd_IsDelete__Q211daObjOspbox28@unnamed@d_a_obj_ospbox_cpp@FPv */
BOOL Mthd_IsDelete(void* i_this) {
    return ((daObjOspbox::Act_c*)i_this)->IsDelete();
}

static actor_method_class Mthd_Table = {
    (process_method_func)Mthd_Create,
    (process_method_func)Mthd_Delete,
    (process_method_func)Mthd_Execute,
    (process_method_func)Mthd_IsDelete,
    (process_method_func)Mthd_Draw,
};
}; // namespace
}; // namespace daObjOspbox

actor_process_profile_definition g_profile_Obj_Ospbox = {
    /* LayerID      */ fpcLy_CURRENT_e,
    /* ListID       */ 0x0003,
    /* ListPrio     */ fpcPi_CURRENT_e,
    /* ProcName     */ PROC_Obj_Ospbox,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daObjOspbox::Act_c),
    /* SizeOther    */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Priority     */ PRIO_Obj_Ospbox,
    /* Actor SubMtd */ &daObjOspbox::Mthd_Table,
    /* Status       */ fopAcStts_NOCULLEXEC_e | fopAcStts_CULL_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* CullType     */ fopAc_CULLBOX_CUSTOM_e,
};
